### ISSUE TITLE
Moving component and TopologicalNode together on diagram

### ISSUE THREAD

**Issue by m-mirz** [sogno-platform/pintura#19]
I can now drop components into the diagram but when I try to move them around either the component itself or its TopologicalNode is moved but not both.

In the screenshot, you can see how it looks like after moving the components / nodes around.

![pintura-issue](https://user-images.githubusercontent.com/16180422/100587188-87fd5b00-32f0-11eb-9348-5bbadaf22f0a.png)

**Comment by richardmarston** [comment]
In the picture there is an ACLineSegment, an EnergyConsumer and a SynchronousMachine. Do you mean that the Terminals don't follow the components around?

**Comment by richardmarston** [comment]
I think maybe it doesn't make sense to be able to move the Terminal at all. It should be selectable so that you can see / update the attributes but not draggable. Then the only way to adjust the location is to move the component or change the orientation so that the terminal move to N/S/E/W of the component. What do you think?

**Comment by m-mirz** [comment]
Yes, I think what you propose is the best solution.

**Comment by richardmarston** [comment]
Fixed in commit https://github.com/sogno-platform/pintura/commit/8265f89ea81184e71ae7d61162d1e23aaee0b597
